services:
  # ── Web API ────────────────────────────────────────────
  - type: web
    plan: free
    name: sentimeter-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - fromGroup: sentimeter